// lib/constants.ts

export const IMAGES = {
  logo: "/logo.png",
  hero: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&q=80&w=1200",
  education: "https://images.unsplash.com/photo-1594122230689-45899d9e6f69?auto=format&fit=crop&q=80&w=800",
  medicalCamp: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=800",
  charityWelfare: "https://images.unsplash.com/photo-1605647540924-852290f6b0d5?auto=format&fit=crop&q=80&w=800",
  volunteerBoard: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800",
  yogaCamp: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
  womenEmpower: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800",
  chairman: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400",
  trustee2: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400",
  trustee3: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400",
  trustee4: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400",
};

export const DICTIONARY = {
  en: {
    trustName: "Late Popatbhai Premjibhai Maniya Trust",
    fullName: "Late Popatbhai Premjibhai Maniya (P.P. Maniya) Education & Medical Trust",
    regLabel: "Registered Charitable Trust",
    cert12a: "12A Certified",
    cert80g: "80G Tax Exempt",
    csrReady: "CSR Partner Ready",
    donateCta: "DONATE NOW",
    tagline: "Serving Humanity Through Education, Healthcare & Community Development",
    subTagline: "Dedicated to uplifting rural and underprivileged lives through structured educational scholarships, premium medical assistance, state-wide community service, and long-term socio-economic empowerment across India.",
    knowWork: "Explore Activities",
    beVolunteer: "Volunteer With Us",
    home: "Home",
    about: "About Trust",
    activities: "Activities & Projects",
    trustees: "Trustees & Governance",
    events: "Events & Gallery",
    contact: "Donate & Contact",
    address: "A/35, Rachna Society, Kapodara Char Rasta, Varachha Road, Surat-395006, Gujarat",
    phone: "+91 98251 45431",
    email: "info@ppmaniyatrust.org",
    officeHours: "Mon - Sat: 9:00 AM - 6:00 PM",
    chairmanQuote: "True compassion lies not just in feeling sorrow, but in creating durable, community-driven pathways to health and education.",
    chairmanName: "Shri Batukbhai P. Maniya",
    chairmanTitle: "Trust Chairman & Founder",
    impactLives: "Lives Impacted",
    impactMedical: "Medical Camp Attendees",
    impactStudents: "Students Supported",
    impactCamps: "Camps Organized",
    impactVolunteers: "Active Volunteers",
    impactYears: "Years of Commitment",
  },
  hi: {
    trustName: "स्व. पोपटभाई प्रेमजीभाई मनिया ट्रस्ट",
    fullName: "स्वर्गीय पोपटभाई प्रेमजी भाई मनिया (पी.पी. मनिया) शिक्षा और चिकित्सा ट्रस्ट",
    regLabel: "पंजीकृत धर्मार्थ ट्रस्ट",
    cert12a: "12A प्रमाणित",
    cert80g: "80G कर छूट",
    csrReady: "CSR भागीदार तैयार",
    donateCta: "दान करें",
    tagline: "शिक्षा, स्वास्थ्य सेवा और सामुदायिक विकास के माध्यम से मानवता की सेवा",
    subTagline: "भारत भर में संरचित शैक्षिक छात्रवृत्ति, प्रीमियम चिकित्सा सहायता, राज्यव्यापी सामुदायिक सेवा और दीर्घकालिक सामाजिक-आर्थिक सशक्तिकरण के माध्यम से ग्रामीण और वंचित जीवन के उत्थान के लिए समर्पित।",
    knowWork: "हमारे कार्य जानें",
    beVolunteer: "स्वयंसेवक बनें",
    home: "मुख्य पृष्ठ",
    about: "ट्रस्ट के बारे में",
    activities: "गतिविधियां और परियोजनाएं",
    trustees: "ट्रस्टी और शासन",
    events: "कार्यक्रम और गैलरी",
    contact: "दान और संपर्क",
    address: "ए/35, रचना सोसाइटी, कपोदरा चार रास्ता, वराछा रोड, सूरत-395006, गुजरात",
    phone: "+91 98251 45431",
    email: "info@ppmaniyatrust.org",
    officeHours: "सोम - शनि: सुबह 9:00 - शाम 6:00",
    chairmanQuote: "सच्ची करुणा न केवल दुख महसूस करने में है, बल्कि स्वास्थ्य और शिक्षा के लिए स्थायी, समुदाय-संचालित मार्ग बनाने में है।",
    chairmanName: "श्री बटुकभाई पी. मनिया",
    chairmanTitle: "ट्रस्ट अध्यक्ष और संस्थापक",
    impactLives: "प्रभावित जीवन",
    impactMedical: "चिकित्सा लाभार्थी",
    impactStudents: "समर्थित छात्र",
    impactCamps: "आयोजित चिकित्सा शिविर",
    impactVolunteers: "सक्रिय स्वयंसेवक",
    impactYears: "प्रतिबद्धता के वर्ष",
  },
  gu: {
    trustName: "સ્વ. પોપટભાઈ પ્રેમજીભાઈ મણીયા ટ્રસ્ટ",
    fullName: "સ્વર્ગસ્થ પોપટભાઈ પ્રેમજીભાઈ મણીયા (પી.પી. મણીયા) એજ્યુકેશન એન્ડ મેડિકલ ટ્રસ્ટ",
    regLabel: "રજિસ્ટર્ડ ચેરિટેબલ ટ્રસ્ટ",
    cert12a: "12A પ્રમાણિત",
    cert80g: "80G ટેક્સ મુક્તિ",
    csrReady: "CSR પાર્ટનર સજ્જ",
    donateCta: "દાન આપો",
    tagline: "શિક્ષણ, આરોગ્ય અને સામુદાયિક વિકાસ દ્વારા માનવતાની સેવા",
    subTagline: "ગુજરાત અને દેશભરમાં વંચિતો સુધી શિક્ષણ સહાય, આરોગ્ય સહાય અને સર્વગ્રાહી સામાજિક અને આર્થિક ઉત્થાન પહોંચાડવા કટિબદ્ધ ટ્રસ્ટ.",
    knowWork: "અમારી પ્રવૃત્તિઓ",
    beVolunteer: "સ્વયંસેવક બનો",
    home: "હોમ પેજ",
    about: "ટ્રસ્ટ વિશે",
    activities: "પ્રવૃત્તિઓ અને પ્રોજેક્ટ્સ",
    trustees: "ટ્રસ્ટીઓ અને ગવર્નન્સ",
    events: "ઇવેન્ટ્સ અને ગેલેરી",
    contact: "દાન અને સંપર્ક",
    address: "એ/૩૫, રચના સોસાયટી, કાપોદ્રા ચાર રસ્તા, વરાછા રોડ, સુરત-૩૯૫૦૦૬, ગુજરાત",
    phone: "+91 98251 45431",
    email: "info@ppmaniyatrust.org",
    officeHours: "સોમ - શનિ: સવારે ૯ થી સાંજે ૬",
    chairmanQuote: "સાચી કરુણા માત્ર હૃદયમાં દુખ રાખવાથી નહીં, પણ લોકો માટે ટકાઉ શિક્ષણ અને તબીબી વ્યવસ્થાઓ ઊભી કરવાથી સાબિત થાય છે.",
    chairmanName: "શ્રી બટુકભાઈ પી. મણીયા",
    chairmanTitle: "ટ્રસ્ટ પ્રમુખ અને સ્થાપક",
    impactLives: "લાભાન્વિતો ની કુલ સંખ્યા",
    impactMedical: "તબીબી સેવાનો લાભ મેળવનાર",
    impactStudents: "વિદ્યાર્થીઓને શિષ્યવૃત્તિ",
    impactCamps: "યોજાયેલા મેડિકલ કેમ્પ",
    impactVolunteers: "સક્રિય સ્વયંસેવકો",
    impactYears: "સેવાના વર્ષો",
  },
};

export type Lang = "en" | "hi" | "gu";
export type DictType = typeof DICTIONARY.en;